global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "second-exporter"
    scrape_interval: 5s
    static_configs:
    - targets: ["34.207.112.179:9100"]

rule_files:
  - rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]