server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: nginx_access_log
  static_configs:
  - targets:
      - loki
    labels:
      job: nginx_access_log
      __path__: /opt/nginx_access.log
- job_name: httpd_access_log
  static_configs:
  - targets:
      - loki
    labels:
      job: httpd_access_log
      __path__: /opt/httpd_access.log